# Generated by Django 2.1.15 on 2020-05-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_opportunity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='recruiter',
            field=models.CharField(default='asaadhalabi', max_length=100, verbose_name='recruiter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='link'),
        ),
    ]
