# Generated by Django 2.1.15 on 2020-05-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_auto_20200511_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='recruiter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='recruiter'),
        ),
    ]
